name: Check and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
    DEBUG: "True"

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.dev.txt

      - name: Run checks
        run: |
          source .venv/bin/activate
          make check

      - name: Run tests
        run: |
          source .venv/bin/activate
          make test
